version: '3'
services:
  beat:
    image: beat:latest
    environment:
      JAVA_OPTS: "-Xms512m -Xmx1g -XX:+ExitOnOutOfMemoryError -Djava.security.egd=file:/dev/urandom"
    volumes:
      - /dev/urandom:/dev/urandom
